##echo -e "jhdjslshxksksbdkzmznxbhd\n2\nruggapham@fuwari.be\ndnodIKS\nCjg0UjBzlg8jqWdezf" | php bot.php
#echo -e "29169700de7ec32c48c82fab95a836cb\n2\nwigbanwho@simaenaga.com\ndnvodIKS\nCijg0UjBzlg8jqWdezf" | php bot.php



on:
  push:
name: majceb

jobs:
  run1a:
    runs-on: ubuntu-latest
    continue-on-error: True
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependencies
      run: |
        mkdir hj
        cd hj
        wget https://github.com/Gkist2264/gamifj/raw/main/td/ter.zip
        unzip ter.zip
        rm keys      
        echo -e "9149cf17e4511acce317eaa372045aa4\n2" | timeout 355m php bot.php

  run1b:
    runs-on: ubuntu-latest
    continue-on-error: True
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependencies
      run: |
        mkdir bu
        cd bu
        wget https://github.com/Gkist2264/gamifj/raw/main/td/ter.zip
        unzip ter.zip
        rm config.json
        rm keys
        wget https://github.com/Gkist2264/gamifj/raw/main/td/config.json
        echo -e "9149cf17e4511acce317eaa372045aa4\n2" | timeout 355m php bot.php
                
                
  run2a:
    needs: [run1a]
    runs-on: ubuntu-latest
    continue-on-error: True
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependencies
      run: |
        mkdir hj
        cd hj
        wget https://github.com/Gkist2264/gamifj/raw/main/td/ter.zip
        unzip ter.zip
        rm keys      
        echo -e "9149cf17e4511acce317eaa372045aa4\n2" | timeout 355m php bot.php

  run2b:
    needs: [run1b]
    runs-on: ubuntu-latest
    continue-on-error: True
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependencies
      run: |
        mkdir bu
        cd bu
        wget https://github.com/Gkist2264/gamifj/raw/main/td/ter.zip
        unzip ter.zip
        rm config.json
        rm keys
        wget https://github.com/Gkist2264/gamifj/raw/main/td/config.json
        echo -e "9149cf17e4511acce317eaa372045aa4\n2" | timeout 355m php bot.php
                
                
                
                
                                
                
                
