##echo -e "jhdjslshxksksbdkzmznxbhd\n2\nruggapham@fuwari.be\ndnodIKS\nCjg0UjBzlg8jqWdezf" | php bot.php
#echo -e "29169700de7ec32c48c82fab95a836cb\n2\nwigbanwho@simaenaga.com\ndnvodIKS\nCijg0UjBzlg8jqWdezf" | php bot.php



on:
  push:
name: majce

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependencies
      run: |
        mkdir hj
        cd hj
        wget https://github.com/Gkist2264/gamifj/raw/main/td/ter.zip
        unzip ter.zip
        echo -e "2" | php bot.php
        
